/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {


       String actual =  App.getJson();
       String expected = actual;

       assertEquals("app should have a greeting", expected, actual );
    }
}
