/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.nio.BufferOverflowException;
import java.util.Scanner;
import java.util.ArrayList;
import java.util.StringJoiner;

import com.google.gson.JsonParser;



public class App {


    public static void main(String[] args) {


    }


    public static String getJson() {
        Gson gson = new Gson();

        String path = "src/main/java/quotes/recentquotes.json";

        try {
            Scanner scanner = new Scanner(new File(path));
            //boolean bool = scanner.hasNextLine();
            StringJoiner joinString = new StringJoiner(" ");
            while (scanner.hasNextLine()) {
                joinString.add(scanner.nextLine());

            }
//          // String firstLine = scanner.findInLine("author");
//         //   ArrayList<String> test = new Gson().fromJson(path, ArrayList.class);
//           Author firstQuote = gson.fromJson(firstLine, Author.class);
////          System.out.println(firstQuote.toString());
////            System.out.println(bool);
            Author[] authorArray = gson.fromJson(joinString.toString(), Author[].class);
            return authorArray[3].toString();


        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return "no info";
    }

}
