/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.util.Scanner;
import java.util.StringJoiner;


public class App {


    public static void main(String[] args) {


    }

// Tutorialpoint.com, geeks for geeks, and stackoverflow were all referenced for research for this lab
    public static String getJson() {
        Gson gson = new Gson();

        String path = "src/main/java/quotes/recentquotes.json";

        try {
            Scanner scanner = new Scanner(new File(path));

            StringJoiner joinString = new StringJoiner(" ");
            while (scanner.hasNextLine()) {
                joinString.add(scanner.nextLine());

            }
            int random = (int)(Math.random() * 20) + 1;
            Author[] authorArray = gson.fromJson(joinString.toString(), Author[].class);
            System.out.println(authorArray[random].toString());
            return authorArray[random].toString();

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return "no info";
    }

}
